# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "SONGS" ("name" VARCHAR NOT NULL,"genre" VARCHAR NOT NULL,"duration_sec" INTEGER NOT NULL,"album" BIGINT NOT NULL,"id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);
alter table "SONGS" add constraint "album_fk" foreign key("album") references "SONGS"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "SONGS" drop constraint "album_fk";
drop table "SONGS";

